program Rural7;

uses
  Forms,
  Windows,
  SysUtils,
  MidasLib,
  Dialogs,
  IniFiles,
  UPrin in 'UPrin.pas' {FPrin},
  UCadCobranca in 'UCadCobranca.pas' {FCadCobranca},
  UCadSetorVencRR in 'UCadSetorVencRR.pas' {FCadSetorVencRR},
  UCadDescontos in 'UCadDescontos.pas' {FCadDescontos},
  UCadTabCalculo in 'UCadTabCalculo.pas' {FCadTabCalculo},
  UCadClassifica in 'UCadClassifica.pas' {FCadClassifica},
  UCadPontos in 'UCadPontos.pas' {FCadPontos},
  UCadConfCalc in 'UCadConfCalc.pas' {FCadConfCalc},
  UCadRural in 'UCadRural.pas' {FCadRural},
  UCalcRural in 'UCalcRural.pas' {FCalcRural},
  UConsRural in 'UConsRural.pas' {FConsRural},
  URelRolLancRR in 'URelRolLancRR.pas' {FRelRolLancRR},
  URelEtiquetaRR in 'URelEtiquetaRR.pas' {FRelEtiquetaRR},
  URelGuiasRR in 'URelGuiasRR.pas' {FRelGuiasRR},
  UCadTransfRR in 'UCadTransfRR.pas' {FCadTransfRR},
  URelTransfPropRR in 'URelTransfPropRR.pas' {FRelTransfPropRR},
  URelRolRR in 'URelRolRR.pas' {FRelRolRR},
  UConsProVegISO in 'UConsProVegISO.pas' {FConsProVegISO},
  UConsProAni in 'UConsProAni.pas' {FConsProAni},
  UConsRRAreas in 'UConsRRAreas.pas' {FConsRRAreas},
  UExportaLanc in 'UExportaLanc.pas' {FExportaLanc},
  UCadObrigRUR in 'UCadObrigRUR.pas' {FCadObrigRUR},
  URelDescontos in 'URelDescontos.pas' {FRelDescontos},
  URelTabCalculo in 'URelTabCalculo.pas' {FRelTabCalculo},
  URelCodCob in 'URelCodCob.pas' {FRelCodCob},
  UMudaCadastroRural in 'UMudaCadastroRural.pas' {FMudaCadastroRural},
  UClasse_PesqRur in 'UClasse_PesqRur.pas',
  UClasse_Agua in '..\Agua\UClasse_Agua.pas',
  UDMAgua in '..\Agua\UDMAgua.pas' {DMAgua: TDataModule},
  UdmDSnapAG in '..\Agua\UdmDSnapAG.pas' {dmDSnapAG: TDataModule},
  UClasse_PesqAgua in '..\Agua\UClasse_PesqAgua.pas',
  UClasse_PesqAtend in '..\Atendimento\UClasse_PesqAtend.pas',
  UClasse_Cemiterio in '..\Cemiterio\UClasse_Cemiterio.pas',
  UDMCemi in '..\Cemiterio\UDMCemi.pas' {dmCEMI: TDataModule},
  UClasse_PesqCemi in '..\Cemiterio\UClasse_PesqCemi.pas',
  URelGenericoSimples in '..\Diversas\URelGenericoSimples.pas' {FRelGenericoSimples},
  UGenerico in '..\Diversas\UGenerico.pas' {FGenerico},
  URelGenerico in '..\Diversas\URelGenerico.pas' {FRelGenerico},
  UClasse_Protocolo in '..\Diversas\UClasse_Protocolo.pas',
  UClasse_Diversas in '..\Diversas\UClasse_Diversas.pas',
  UDMDiversas in '..\Diversas\UDMDiversas.pas' {DMDIV: TDataModule},
  UClasse_PesqDiverso in '..\Diversas\UClasse_PesqDiverso.pas',
  Unit3 in '..\Editor\Unit3.pas' {frmEditor},
  dmActions in '..\Editor\dmActions.pas' {rvActionsResource: TDataModule},
  UClasse_Financeiro in '..\Financeiro\UClasse_Financeiro.pas',
  UDMFin in '..\Financeiro\UDMFin.pas' {dmFin: TDataModule},
  UClasse_PesqFIn in '..\Financeiro\UClasse_PesqFIn.pas',
  APIMedral in '..\GeoReferenciamento\Medral\APIMedral.pas',
  UFuncoesMedral in '..\GeoReferenciamento\Medral\UFuncoesMedral.pas',
  UDMF in '..\Imobiliario\UDMF.pas' {DMF: TDataModule},
  UDMIPTU in '..\Imobiliario\UDMIPTU.pas' {DMIPTU: TDataModule},
  UClasse_PesqImob in '..\Imobiliario\UClasse_PesqImob.pas',
  UClasse_Juridico in '..\Juridico\UClasse_Juridico.pas',
  UDMJur in '..\Juridico\UDMJur.pas' {dmJur: TDataModule},
  UClasse_PesqJur in '..\Juridico\UClasse_PesqJur.pas',
  System_log in '..\Log\System_log.pas',
  Dados_Log in '..\Log\Dados_Log.pas' {dmLog: TDataModule},
  IB_CriaDB in '..\Log\IB_CriaDB.pas',
  UDMMOBI in '..\Mobiliario\UDMMOBI.pas' {dmMobi: TDataModule},
  UClasse_Mobiliario in '..\Mobiliario\UClasse_Mobiliario.pas',
  UClasse_PesqMobi in '..\Mobiliario\UClasse_PesqMobi.pas',
  UDM in '..\Principal\UDM.pas' {dm: TDataModule},
  UDMMAPIMail in '..\Principal\UDMMAPIMail.pas' {DMMAPIMail: TDataModule},
  UDMSSE in '..\Principal\UDMSSE.pas' {dmSSE: TDataModule},
  funcoes in '..\Principal\funcoes.pas',
  PackForm in '..\Principal\PackForm.pas' {Form1},
  aguarde in '..\Principal\aguarde.pas' {frmaguarde},
  Fmxutils in '..\Principal\Fmxutils.pas',
  TrataErros in '..\Principal\TrataErros.pas',
  UEMail in '..\Principal\UEMail.pas' {FEMail},
  USobre in '..\Principal\USobre.pas' {FSobre},
  UClasse_Principal in '..\Principal\UClasse_Principal.pas',
  WBFuncs in '..\Principal\WBFuncs.pas',
  FunRede in '..\Principal\FunRede.pas',
  UClasse_SCPI in '..\Principal\UClasse_SCPI.pas',
  UDMSCPI in '..\Principal\UDMSCPI.pas' {dmSCPI: TDataModule},
  UFundo5 in '..\Principal\UFundo5.pas' {FrmFundo5},
  UFundo4 in '..\Principal\UFundo4.pas' {FrmFundo4},
  UFundo3 in '..\Principal\UFundo3.pas' {FrmFundo3},
  UFundo2 in '..\Principal\UFundo2.pas' {FrmFundo2},
  UFundo in '..\Principal\UFundo.pas' {FrmFundo},
  UClasseDSP_NIM in '..\Principal\UClasseDSP_NIM.pas',
  HID in '..\Principal\HID.pas',
  UFastReportFuncoes in '..\Principal\UFastReportFuncoes.pas',
  UDMPrin in '..\Principal\UDMPrin.pas' {dmPrin: TDataModule},
  UClasse_UsuariosSIA in '..\Principal\UClasse_UsuariosSIA.pas',
  UClasse_PesqPrin in '..\Principal\UClasse_PesqPrin.pas',
  UClasse_PesqProt in '..\Principal\UClasse_PesqProt.pas',
  UClasse_Acoes in '..\Principal\UClasse_Acoes.pas',
  uValida_Chave in '..\..\..\Projeto_Chave_Validade\Valida_Chave\uValida_Chave.pas',
  UDMOS in '..\Serviços\UDMOS.pas' {DMOS: TDataModule},
  UClasse_Servicos in '..\Serviços\UClasse_Servicos.pas',
  UDMServ in '..\Serviços\UDMServ.pas' {dmServ: TDataModule},
  URelatorios in '..\Principal\URelatorios.pas' {FRelatorios},
  USelecao in '..\Diversas\USelecao.pas' {FSelecao},
  UConsContrib in '..\Principal\UConsContrib.pas' {FConsContrib},
  UConsIPTU in '..\Imobiliario\UConsIPTU.pas' {FConsIPTU},
  UConsMobil in '..\Mobiliario\UConsMobil.pas' {FConsMobil},
  UCadContribuintes in '..\Principal\UCadContribuintes.pas' {FCadContribuintes},
  URelContribuintes in '..\Principal\URelContribuintes.pas' {FRelContribuintes},
  UCadLogradouros in '..\Principal\UCadLogradouros.pas' {FCadLogradouros},
  URelLogra in '..\Principal\URelLogra.pas' {FRelLogra},
  UCadBairros in '..\Principal\UCadBairros.pas' {FCadBairros},
  URelBairros in '..\Principal\URelBairros.pas' {FRelBairros},
  UCadHistoricos in '..\Principal\UCadHistoricos.pas' {FCadHistoricos},
  URelHistoricos in '..\Principal\URelHistoricos.pas' {FRelHistoricos},
  URelEtiqueta_CNT in '..\Principal\URelEtiqueta_CNT.pas' {FRelEtiqueta_CNT},
  UConsultaLancamentos in '..\Financeiro\UConsultaLancamentos.pas' {FConsultaLancamento},
  UPesquisaDivida in '..\Financeiro\UPesquisaDivida.pas' {FPesquisaDivida},
  URelExtratoGuia in '..\Financeiro\URelExtratoGuia.pas' {FRelExtratoGuia},
  URelExtrato in '..\Financeiro\URelExtrato.pas' {FRelExtrato},
  URelListagemDebitos in '..\Financeiro\URelListagemDebitos.pas' {FRelListagemDebitos},
  UConsultaGuias in '..\Financeiro\UConsultaGuias.pas' {FConsultaGuias},
  URelExtratoParcelamento in '..\Financeiro\URelExtratoParcelamento.pas' {FRelExtratoParcelamento},
  UAlteraVencimento in '..\Financeiro\UAlteraVencimento.pas' {FAlteraVencimento},
  UConsSite in '..\Principal\UConsSite.pas' {FConsSite},
  URelVincCNT in '..\Principal\URelVincCNT.pas' {FRelVincCNT},
  URelCidades in '..\Principal\URelCidades.pas' {FRelCidades},
  UCadCidades in '..\Principal\UCadCidades.pas' {FCadCidades},
  UConsTerrCemi in '..\Cemiterio\UConsTerrCemi.pas' {FConsTerrCemi},
  UCadTerrenoCemi in '..\Cemiterio\UCadTerrenoCemi.pas' {FCadTerrenoCemi},
  UCadTransfCEMI in '..\Cemiterio\UCadTransfCEMI.pas' {FCadTransfCEMI},
  URelTerrenosCemi in '..\Cemiterio\URelTerrenosCemi.pas' {FRelTerrenosCemi},
  URelTransfPropCEMI in '..\Cemiterio\URelTransfPropCEMI.pas' {FRelTransfPropCEMI},
  UConsAgua in '..\Agua\UConsAgua.pas' {FConsAgua},
  UCadHidro in '..\Agua\UCadHidro.pas' {FCadHidro},
  UConsHidrometro in '..\Agua\UConsHidrometro.pas' {FConsHidrometro},
  UConsAtividade in '..\Mobiliario\UConsAtividade.pas' {FConsAtividades},
  UCadAtivDesdo in '..\Mobiliario\UCadAtivDesdo.pas' {FCadAtivDesdo},
  UCadAtividade in '..\Mobiliario\UCadAtividade.pas' {FCadAtividade},
  URelAtvDesdobro in '..\Mobiliario\URelAtvDesdobro.pas' {FRelAtvDesdobro},
  URelGrupo in '..\Mobiliario\URelGrupo.pas' {FRelGrupo},
  UGuiasFin in '..\Financeiro\UGuiasFin.pas' {FRelGuiasFin},
  UConsultaDivida in '..\Financeiro\UConsultaDivida.pas' {FconsultaDivida},
  UCarneParcelamento in '..\Financeiro\UCarneParcelamento.pas' {FRelCarneParcelamento},
  URelTermoConfissao in '..\Financeiro\URelTermoConfissao.pas' {FRelTermoConfissao},
  URelPedidoParcelamento in '..\Financeiro\URelPedidoParcelamento.pas' {FRelPedidoParcelamento},
  URelExtratoContribuinte in '..\Financeiro\URelExtratoContribuinte.pas' {FRelExtratoContribuinte},
  URelListagemDebitosContribuinte in '..\Financeiro\URelListagemDebitosContribuinte.pas' {FRelListagemDebitosContribuinte},
  URelGuiasIPTU in '..\Imobiliario\URelGuiasIPTU.pas' {FRelGuiasIPTU},
  UEstornoParcelamento in '..\Financeiro\UEstornoParcelamento.pas' {FEstornoParcelamento},
  UCadastraOrigem in '..\Financeiro\UCadastraOrigem.pas' {FCadOrigemParcelamento},
  URelGuiasMobi in '..\Mobiliario\URelGuiasMobi.pas' {FRelGuiasMobi},
  UFuncoesBaixas in '..\Financeiro\UFuncoesBaixas.pas',
  URelGuiasAgua in '..\Agua\URelGuiasAgua.pas' {FRelGuiasAgua},
  UCompensaValores in '..\Financeiro\UCompensaValores.pas' {FCompensaValores},
  UEstornaCompensaValores in '..\Financeiro\UEstornaCompensaValores.pas' {FEstornaCompensaValores},
  UEstornaBaixaDividas in '..\Financeiro\UEstornaBaixaDividas.pas' {FEstornaBaixaDividas},
  UBaixaDividas in '..\Financeiro\UBaixaDividas.pas' {FBaixaDividas},
  UCadITBI in '..\Diversas\UCadITBI.pas' {FCadITBI},
  UCadCertidoes in '..\Diversas\UCadCertidoes.pas' {FCadCertidoes},
  UCadGeral in '..\Diversas\UCadGeral.pas' {FCadDiversas},
  UCalculaReceitas in '..\Diversas\UCalculaReceitas.pas' {FCalculaReceitas},
  URelGuias in '..\Diversas\URelGuias.pas' {FRelGuias},
  URelGeral in '..\Diversas\URelGeral.pas' {FRelGeral},
  UConsHisPadrao in '..\Diversas\UConsHisPadrao.pas' {FConsHisPadrao},
  UCadHisPadrao in '..\Diversas\UCadHisPadrao.pas' {FCadHisPadrao},
  UZoomHisto in '..\Diversas\UZoomHisto.pas' {FZoomHisto},
  URelITBI in '..\Diversas\URelITBI.pas' {FRelITBI},
  UConsCert in '..\Diversas\UConsCert.pas' {FConsCert},
  URelCertidoes in '..\Diversas\URelCertidoes.pas' {FRelCertidoes},
  UCadValCertidoes in '..\Diversas\UCadValCertidoes.pas' {FCadValCertidoes},
  UCadUC in '..\Agua\UCadUC.pas' {FCadUC},
  UCalcAgua in '..\Agua\UCalcAgua.pas' {FGCalcAgua},
  UManLeituras in '..\Agua\UManLeituras.pas' {FManLeituras},
  UCadTransfAGUA in '..\Agua\UCadTransfAGUA.pas' {FCadTransfAgua},
  URelTransfPropAGUA in '..\Agua\URelTransfPropAGUA.pas' {FRelTransfPropAGUA},
  UApliacao in '..\Agua\UApliacao.pas' {FApliacao},
  URelRolCadastralAgua in '..\Agua\URelRolCadastralAgua.pas' {FRelRolCadastral},
  URelAlteracoesAgua in '..\Agua\URelAlteracoesAgua.pas' {FRelAlteracoesAgua},
  UGRefaturaAG in '..\Agua\UGRefaturaAG.pas' {FGRefaturaAG},
  UDuplicaAG in '..\Agua\UDuplicaAG.pas' {FDuplicaAG},
  UCadEmpre in '..\Mobiliario\UCadEmpre.pas' {FCadEmpre},
  UCadEscritorio in '..\Mobiliario\UCadEscritorio.pas' {FCadEscritorio},
  URelEscritorio in '..\Mobiliario\URelEscritorio.pas' {FRelEscritorio},
  UGeraAnual in '..\Mobiliario\UGeraAnual.pas' {FGeraAnual},
  URelAlvaraEventual in '..\Mobiliario\URelAlvaraEventual.pas' {FRelAlvaraEventual},
  URelAlvara in '..\Mobiliario\URelAlvara.pas' {FRelAlvara},
  URelAlvaraVeiculo in '..\Mobiliario\URelAlvaraVeiculo.pas' {FRelAlvaraVeiculo},
  URelRol in '..\Mobiliario\URelRol.pas' {FRelRol},
  UCadAlvaras in '..\Diversas\UCadAlvaras.pas' {FCadAlvaras},
  URelGuiaAlvara in '..\Diversas\URelGuiaAlvara.pas' {FRelGuiaAlvara},
  URelAlvaraDiversos in '..\Diversas\URelAlvaraDiversos.pas' {FRelAlvaraDiversos},
  URelMapaCalcIPTU in '..\Imobiliario\URelMapaCalcIPTU.pas' {FRelMapaCalcIPTU},
  UCadImoveis in '..\Imobiliario\UCadImoveis.pas' {FCadImoveis},
  UMenuTabGerais in '..\Imobiliario\UMenuTabGerais.pas' {FMenuTabGerais},
  UConfCalc in '..\Imobiliario\UConfCalc.pas' {FConfCalc},
  UCadSecao in '..\Imobiliario\UCadSecao.pas' {FCadSecao},
  URelSecoes in '..\Imobiliario\URelSecoes.pas' {FRelSecoes},
  UCadAgrupa in '..\Imobiliario\UCadAgrupa.pas' {FCadAgrupa},
  URelAgrupa in '..\Imobiliario\URelAgrupa.pas' {FRelAgrupa},
  UDuplicaZona in '..\Imobiliario\UDuplicaZona.pas' {FDuplicaZonas},
  UCadValCRT in '..\Imobiliario\UCadValCRT.pas' {FCadValCRT},
  URelValCRT in '..\Imobiliario\URelValCRT.pas' {FRelValCRT},
  UCadZonaEdif in '..\Imobiliario\UCadZonaEdif.pas' {FCadZonaEdif},
  URelZonaEdif in '..\Imobiliario\URelZonaEdif.pas' {FRelZonaEdif},
  UCadCaractGerais in '..\Imobiliario\UCadCaractGerais.pas' {FCadCaractGerais},
  URelCaractGerais in '..\Imobiliario\URelCaractGerais.pas' {FRelCaractGerais},
  UCadSetorVenc in '..\Imobiliario\UCadSetorVenc.pas' {FCadSetorVenc},
  UCadCodCob in '..\Imobiliario\UCadCodCob.pas' {FCadCodCob},
  URelExtratoValorVenal in '..\Imobiliario\URelExtratoValorVenal.pas' {FRelExtratoValorVenal},
  UCadTransf in '..\Imobiliario\UCadTransf.pas' {FCadTransf},
  URelTransfProp in '..\Imobiliario\URelTransfProp.pas' {FRelTransfProp},
  URelRolIPTU in '..\Imobiliario\URelRolIPTU.pas' {FRelRolIPTU},
  URelPedIsencao in '..\Imobiliario\URelPedIsencao.pas' {FRelPedIsencao},
  URelAlteracoesIPTU in '..\Imobiliario\URelAlteracoesIPTU.pas' {FRelAlteracoesIPTU},
  FunIPTU in '..\Imobiliario\FunIPTU.pas',
  URelImoveis in '..\Imobiliario\URelImoveis.pas' {FRelImoveis},
  URelHisCad in '..\Imobiliario\URelHisCad.pas' {FRelHisCad},
  URelPreVV in '..\Imobiliario\URelPreVV.pas' {FRelPreVV},
  UCalculaIPTU in '..\Imobiliario\UCalculaIPTU.pas' {FCalculaIPTU},
  UDuplica in '..\Imobiliario\UDuplica.pas' {FDuplicar},
  TreeFunc in '..\Imobiliario\TreeFunc.pas',
  UCadCartorio in '..\Principal\UCadCartorio.pas' {FCadCartorio},
  URelCartorio in '..\Principal\URelCartorio.pas' {FRelCartorios},
  UConsInfracoes in '..\Atendimento\UConsInfracoes.pas' {FConsInfracoes},
  UCadTabMultas in '..\Diversas\UCadTabMultas.pas' {FCadTabMultas},
  UCadFiscais in '..\Diversas\UCadFiscais.pas' {FCadFiscais},
  UCadInfracao in '..\Diversas\UCadInfracao.pas' {FCadInfracao},
  URelInfracoes in '..\Diversas\URelInfracoes.pas' {FRelInfracoes},
  UDuplicarInfracoes in '..\Diversas\UDuplicarInfracoes.pas' {FDuplicarInfracoes},
  URelHistoricoConsumos in '..\Agua\URelHistoricoConsumos.pas' {FHistoricoConsumos},
  UCadOS in '..\Serviços\UCadOS.pas' {FCadOS},
  URelCadOS in '..\Serviços\URelCadOS.pas' {FRelOS},
  URelCadSS in '..\Serviços\URelCadSS.pas' {FRelSS},
  UConsVeiculosAG in '..\Agua\UConsVeiculosAG.pas' {FConsVeiculosAG},
  UCadSS in '..\Serviços\UCadSS.pas' {FCadSS},
  UConsAgenteAG in '..\Agua\UConsAgenteAG.pas' {FConsAgenteAG},
  UCadTrocaHidro in '..\Agua\UCadTrocaHidro.pas' {FCadTrocaHidro},
  URelCarneAgua in '..\Agua\URelCarneAgua.pas' {FRelCarneAgua},
  URelListaCad in '..\Imobiliario\URelListaCad.pas' {FRelListaCad},
  UCadTrocaLacre in '..\Agua\UCadTrocaLacre.pas' {FCadTrocaLacre},
  IcoWebCep1 in '..\Principal\IcoWebCep1.pas',
  UConsProdutosSIA in '..\Agua\UConsProdutosSIA.pas' {FConsProdutosSIA},
  UConsultaNFnaoDeclarada in '..\Mobiliario\UConsultaNFnaoDeclarada.pas' {FConsultaNFnaoDeclarada},
  UConsTabServAG in '..\Serviços\UConsTabServAG.pas' {FConsTabServAG},
  UAgendaServicosAG in '..\Serviços\UAgendaServicosAG.pas' {FAgendaServicosAG},
  URelListagemDebitosProcesso in '..\Financeiro\URelListagemDebitosProcesso.pas' {FRelListagemDebitosProcesso},
  URelExtratoProcesso in '..\Financeiro\URelExtratoProcesso.pas' {FRelExtratoProcesso},
  USelNim in '..\Principal\USelNim.pas' {FSelNim},
  UFinMensGuias in '..\Financeiro\UFinMensGuias.pas' {FFinMensGuias},
  UCombinaAgrupImob in '..\Imobiliario\UCombinaAgrupImob.pas' {FCombinaAgrupImob},
  uTFSCModulo in '..\Principal\uTFSCModulo.pas',
  UCadObrigIPTU in '..\Imobiliario\UCadObrigIPTU.pas' {FCadObrigIPTU},
  UConsCRTIPT in '..\Imobiliario\UConsCRTIPT.pas' {FConsCRTIPT},
  URelSetVenc in '..\Imobiliario\URelSetVenc.pas' {FRelSetVenc},
  USenhaCustodia in '..\Principal\USenhaCustodia.pas' {FSenhaCustodia},
  URelNotificaInfracoes in '..\Diversas\URelNotificaInfracoes.pas' {FRelNotificaInfracoes},
  UDigitalizaDoc in '..\Principal\UDigitalizaDoc.pas' {FDigitalizaDoc},
  UConsTipoOS in '..\Atendimento\UConsTipoOS.pas' {FConsTipoOS},
  UMostraMapa in '..\Atendimento\UMostraMapa.pas' {FMostraMapa},
  URelCadOSOutros in '..\Serviços\URelCadOSOutros.pas' {FRelOSOutros},
  URelCertidoesAguaEsgoto in '..\Diversas\URelCertidoesAguaEsgoto.pas' {FRelCertidoesAguaEsgoto},
  URelCertidoesDiversos in '..\Diversas\URelCertidoesDiversos.pas' {FRelCertidoesDiversos},
  URelCertidoesImobiliario in '..\Diversas\URelCertidoesImobiliario.pas' {FRelCertidoesImobiliario},
  URelCertidoesImobiliarioRural in '..\Diversas\URelCertidoesImobiliarioRural.pas' {FRelCertidoesImobiliarioRural},
  URelCertidoesMobiliario in '..\Diversas\URelCertidoesMobiliario.pas' {FRelCertidoesMobiliario},
  UCadEntrega in '..\Serviços\UCadEntrega.pas' {FCadEntrega},
  URelEntrega in '..\Serviços\URelEntrega.pas' {FRelEntrega},
  UCadAJProcessos in '..\Financeiro\UCadAJProcessos.pas' {FCadAJProcessos},
  UAJRelatorios in '..\Financeiro\UAJRelatorios.pas' {FAJRelatorios},
  UAJAuxRel in '..\Financeiro\UAJAuxRel.pas' {FAJAuxRel},
  UAJTransfPolo in '..\Financeiro\UAJTransfPolo.pas' {FAJTransfPolo},
  UAJRelTramites in '..\Financeiro\UAJRelTramites.pas' {FAJRelTramites},
  UConsultaLivroDA in '..\Financeiro\UConsultaLivroDA.pas' {FConsultaLivroDA},
  UAJCadLivrosDA in '..\Financeiro\UAJCadLivrosDA.pas' {FAJCadLivrosDA},
  URelLivroDivida in '..\Financeiro\URelLivroDivida.pas' {FRelLivroDivida},
  UConsCRTCMI in '..\Cemiterio\UConsCRTCMI.pas' {FConsCRTCMI},
  URelSegundaViaGeral in '..\Financeiro\URelSegundaViaGeral.pas' {FRelSegundaViaGeral},
  UCadDocumentos in '..\Diversas\UCadDocumentos.pas' {FCadDocumentos},
  UConsDocumentos in '..\Diversas\UConsDocumentos.pas' {FConsDocumentos},
  URelDocumentosAgua in '..\Diversas\URelDocumentosAgua.pas' {FRelDocumentosAgua},
  URelDocumentosDiversos in '..\Diversas\URelDocumentosDiversos.pas' {FRelDocumentosDiversos},
  URelDocumentosImobiliario in '..\Diversas\URelDocumentosImobiliario.pas' {FRelDocumentosImobiliario},
  URelDocumentosMobiliario in '..\Diversas\URelDocumentosMobiliario.pas' {FRelDocumentosMobiliario},
  URelDocumentosRural in '..\Diversas\URelDocumentosRural.pas' {FRelDocumentosRural},
  URelLancaEnglobamentos in '..\Imobiliario\URelLancaEnglobamentos.pas' {FRelLancaEnglobamentos},
  URelListaConfrontantes in '..\Imobiliario\URelListaConfrontantes.pas' {FRelListaConfrontantes},
  URelListaEnglobamentos in '..\Imobiliario\URelListaEnglobamentos.pas' {FRelListaEnglobamentos},
  UDadosRecFederal in '..\Principal\UDadosRecFederal.pas' {FDadosRecFederal},
  UConsObras in '..\Serviços\UConsObras.pas' {FConsObras},
  UCadObra in '..\Serviços\UCadObra.pas' {FCadObra},
  UInfProcJudicial in '..\Financeiro\UInfProcJudicial.pas' {FInfProcJudicial},
  UConsRespObra in '..\Serviços\UConsRespObra.pas' {FConsRespObra},
  UConsTomador in '..\Mobiliario\UConsTomador.pas' {FConsTomador},
  UJCadTomadores in '..\Mobiliario\UJCadTomadores.pas' {FJCadTomadores},
  USelWEB in '..\Mobiliario\USelWEB.pas' {FSelWEB},
  URelAlteracoesMOBIL in '..\Mobiliario\URelAlteracoesMOBIL.pas' {FRelAlteracoesMOBIL},
  ULocalizaCEP in '..\Principal\ULocalizaCEP.pas' {FLocalizaCEP},
  UHisLanDatas in '..\Mobiliario\UHisLanDatas.pas' {FHisLanDatas},
  UConsCDA in '..\Financeiro\UConsCDA.pas' {FConsCDA},
  UJRelTomadores in '..\Mobiliario\UJRelTomadores.pas' {FJRelTomadores},
  UAJQualificaPartes in '..\Financeiro\UAJQualificaPartes.pas' {FAJQualificaPartes},
  UAJCadCertidoes in '..\Financeiro\UAJCadCertidoes.pas' {FAJCadCertidoes},
  USelecaoDividas in '..\Financeiro\USelecaoDividas.pas' {FSelecaoDividas},
  URelListagemObras in '..\Serviços\URelListagemObras.pas' {FRelListagemObras},
  UCadCartaPrec in '..\Juridico\UCadCartaPrec.pas' {FCadCartaPrec},
  URelPrecatoria in '..\Juridico\URelPrecatoria.pas' {FRelPrecatoria},
  UCadPenhora in '..\Juridico\UCadPenhora.pas' {FCadPenhora},
  URelPenhora in '..\Juridico\URelPenhora.pas' {FRelPenhora},
  UCadGarantia in '..\Juridico\UCadGarantia.pas' {FCadGarantia},
  UCadLeiloes in '..\Juridico\UCadLeiloes.pas' {FCadLeiloes},
  UCadRecursos in '..\Juridico\UCadRecursos.pas' {FCadRecursos},
  URelRecurso in '..\Juridico\URelRecurso.pas' {FRelRecurso},
  ULancaDespesa in '..\Juridico\ULancaDespesa.pas' {FLancaDespesa},
  UCadCitacoes in '..\Juridico\UCadCitacoes.pas' {FCadCitacoes},
  UDPGOJustica in '..\Juridico\UDPGOJustica.pas' {FDPGOJustica},
  URelGarantias in '..\Juridico\URelGarantias.pas' {FRelGarantias},
  URelLeiloes in '..\Juridico\URelLeiloes.pas' {FRelLeiloes},
  UCadAJTramites in '..\Financeiro\UCadAJTramites.pas' {FCadAJTramites},
  UAuxAgendamento in '..\Juridico\UAuxAgendamento.pas' {FAuxAgendamento},
  UAuxSuspensao in '..\Juridico\UAuxSuspensao.pas' {FAuxSuspensao},
  UApontaAgenda in '..\Juridico\UApontaAgenda.pas' {FApontaAgenda},
  UConsDeclarante in '..\Principal\UConsDeclarante.pas' {FConsDeclarante},
  UJCadUsuISSWeb in '..\Mobiliario\UJCadUsuISSWeb.pas' {FJCadUsuISSWeb},
  UJTipoUsuISSWeb in '..\Mobiliario\UJTipoUsuISSWeb.pas' {FJTipoUsuISSWeb},
  URelContribuintesDeclarantes in '..\Principal\URelContribuintesDeclarantes.pas' {FRelContribuintesDeclarantes},
  UDuplicaVinculacoesDeclarante in '..\Principal\UDuplicaVinculacoesDeclarante.pas' {FDuplicaVinculacaoDeclarante},
  UCadDivida in '..\Financeiro\UCadDivida.pas' {FCadDivida},
  UDetParcela in '..\Financeiro\UDetParcela.pas' {FDetParcela},
  UCadCredito in '..\Agua\UCadCredito.pas' {FCadCredito},
  URelCreditosAgua in '..\Agua\URelCreditosAgua.pas' {FRelCreditosAgua},
  URelIncosistenciaRetorno in '..\Financeiro\URelIncosistenciaRetorno.pas' {FRelIncosistenciaRetorno},
  URelRecPrincipal in '..\Financeiro\URelRecPrincipal.pas' {FRelRecPrincipal},
  UBaixa in '..\Financeiro\UBaixa.pas' {FBaixa},
  URelPagamentosSimplificado in '..\Financeiro\URelPagamentosSimplificado.pas' {FRelPagamentosSimplificado},
  URelBoletimReceitas in '..\Financeiro\URelBoletimReceitas.pas' {FRelBoletimArrecadacao},
  URelArrecadacao in '..\Financeiro\URelArrecadacao.pas' {FRelArrecadacao},
  UConsReceitaFin in '..\Financeiro\UConsReceitaFin.pas' {FConsReceitaFin},
  UInscrDAFin in '..\Financeiro\UInscrDAFin.pas' {FInscrDAFin},
  URelHisLan in '..\Financeiro\URelHisLan.pas' {FRelHisLan},
  UConsultaDocumentosTermo in '..\Serviços\UConsultaDocumentosTermo.pas' {FConsultaDocumentosTermo},
  UConsultaProcesso in '..\Serviços\UConsultaProcesso.pas' {FConsultaProcesso},
  UCadDocumentoProcesso in '..\Serviços\UCadDocumentoProcesso.pas' {FCadDocumentoProcesso},
  URelDocumentoProcesso in '..\Serviços\URelDocumentoProcesso.pas' {FRelDocumentoProcesso},
  UJRelUsuISSWeb in '..\Mobiliario\UJRelUsuISSWeb.pas' {FJRelUsuISSWeb},
  URelTrocaHidro in '..\Agua\URelTrocaHidro.pas' {FRelTrocaHidro},
  UCadTabCalcITBI in '..\Diversas\UCadTabCalcITBI.pas' {FCadTabCalcITBI},
  URelTabCalcITBI in '..\Diversas\URelTabCalcITBI.pas' {FRelTabCalcITBI},
  UClasse_GoogleMaps in '..\Principal\UClasse_GoogleMaps.pas',
  UConsProcJud in '..\Juridico\UConsProcJud.pas' {FConsProcJud},
  UServCadFisOS in '..\Serviços\UServCadFisOS.pas' {FServCadFisOS},
  UClasse_PesqServ in '..\Serviços\UClasse_PesqServ.pas',
  UConsultaOrdemServico in '..\Serviços\UConsultaOrdemServico.pas' {FConsultaOrdemServico},
  UCadJuntada in '..\Juridico\UCadJuntada.pas' {FCadJuntada},
  Dados_SLog in '..\Protocolo\Log\Dados_SLog.pas' {dmSLog: TDataModule},
  UCadRRCRT in 'UCadRRCRT.pas' {FCadRRCRT},
  UConsSecao in '..\Imobiliario\UConsSecao.pas' {FConsSecao},
  URelCDA in '..\Juridico\URelCDA.pas' {FRelCDA},
  UDetCancelamento in '..\Financeiro\UDetCancelamento.pas' {FDetCancelamento},
  UConsultaReceitas in '..\Diversas\UConsultaReceitas.pas' {FConsultaReceitas},
  aguardesimples in '..\Principal\aguardesimples.pas' {FAguardeSimples},
  UCadSepultamentos in '..\Cemiterio\UCadSepultamentos.pas' {FCadSepultamentos},
  UTransfLocal in '..\Cemiterio\UTransfLocal.pas' {FTransfLocal},
  URelTransLocalCemi in '..\Cemiterio\URelTransLocalCemi.pas' {FRelTransLocalCemi},
  URelSepultamentos in '..\Cemiterio\URelSepultamentos.pas' {FRelSepultamentos},
  UCadObitos in '..\Cemiterio\UCadObitos.pas' {FCadObitos},
  UConsParenteCMI in '..\Cemiterio\UConsParenteCMI.pas' {FConsParenteCMI},
  URelObitos in '..\Cemiterio\URelObitos.pas' {FRelObitos},
  UClasse_PesqEscola in '..\Escola\UClasse_PesqEscola.pas',
  UClasse_Escola in '..\Escola\UClasse_Escola.pas',
  UConsAluno in '..\Escola\UConsAluno.pas' {FConsAluno},
  UConsDiversas in '..\Atendimento\UConsDiversas.pas' {FConsDiversas},
  UConsultaSolicitacao in '..\Serviços\UConsultaSolicitacao.pas' {FConsultaSolicitacao},
  URelRelacaoParcelamentoEstornado in '..\Financeiro\URelRelacaoParcelamentoEstornado.pas' {FRelacaoParcelamentoEstornado},
  USelInscrDivida in '..\Financeiro\USelInscrDivida.pas' {FSelInscrDivida},
  UCadNotPostura in '..\Serviços\UCadNotPostura.pas' {FCadNotPostura},
  URelNotificaPosturasAgua in '..\Serviços\URelNotificaPosturasAgua.pas' {FRelNotificaPosturaAgua},
  URelNotificaPosturasContribuintes in '..\Serviços\URelNotificaPosturasContribuintes.pas' {FRelNotificaPosturaContribuintes},
  URelNotificaPosturasImobiliario in '..\Serviços\URelNotificaPosturasImobiliario.pas' {FRelNotificaPosturaImobiliario},
  URelNotificaPosturasMobiliario in '..\Serviços\URelNotificaPosturasMobiliario.pas' {FRelNotificaPosturaMobiliario},
  URelNotificaPosturasRural in '..\Serviços\URelNotificaPosturasRural.pas' {FRelNotificaPosturaRural},
  UConsultaCompensacao in '..\Financeiro\UConsultaCompensacao.pas' {FConsultaCompensacao},
  URelExtratoCompensacao in '..\Financeiro\URelExtratoCompensacao.pas' {FRelExtratoCompensacao},
  URelTermoConfissaoGuia in '..\Financeiro\URelTermoConfissaoGuia.pas' {FRelTermoConfissaoGuia},
  UCadZonaFiscalRural in 'UCadZonaFiscalRural.pas' {FCadZonaFiscalRural},
  UCancelaCDA in '..\Financeiro\UCancelaCDA.pas' {FCancelaCDA},
  UCadVeiculos in '..\Serviços\UCadVeiculos.pas' {FCadVeiculos},
  URelHisHidrometro in '..\Agua\URelHisHidrometro.pas' {FRelHisHidrometro},
  UCadAgenteCampo in '..\Agua\UCadAgenteCampo.pas' {FCadAgenteCampo},
  URelAgenteCampo in '..\Agua\URelAgenteCampo.pas' {FRelAgenteCampo},
  URelIRCNT in '..\Principal\URelIRCNT.pas' {FRelIRCNT},
  URelCancelados in '..\Financeiro\URelCancelados.pas' {FRelCancelados},
  URelPosicaoProcesso in '..\Financeiro\URelPosicaoProcesso.pas' {FRelPosicaoProcesso},
  URelSegundaViaGeralEscola in '..\Escola\URelSegundaViaGeralEscola.pas' {FRelSegundaViaGeralEscola},
  UBloqFaturas in '..\Agua\UBloqFaturas.pas' {FBloqFaturas},
  UAguardeCopiaArq in '..\Principal\UAguardeCopiaArq.pas' {FAguardeCopiaArq},
  UClasse_IPTU in '..\Imobiliario\UClasse_IPTU.pas',
  UClasse_ITBI in '..\Imobiliario\UClasse_ITBI.pas',
  UCadCobIPTU in '..\Imobiliario\UCadCobIPTU.pas' {FCadCobIPTU},
  UXmlServicosPet in '..\Financeiro\UXmlServicosPet.pas',
  ServicoPJ in '..\Financeiro\ServicoPJ.pas',
  sevenzip in '..\Principal\sevenzip.pas',
  UEnviaPetEletronico in '..\Financeiro\UEnviaPetEletronico.pas' {FEnviaPetEletronico},
  UEnviaPetIntermediario in '..\Juridico\UEnviaPetIntermediario.pas' {FPetIntermediario},
  UXmlPetIntermediario in '..\Financeiro\UXmlPetIntermediario.pas',
  UXmlAjuizamento in '..\Financeiro\UXmlAjuizamento.pas',
  UCertDigitais in '..\Principal\UCertDigitais.pas' {FCertDigitais},
  CAPICOM_TLB in '..\Comp_AssinaturaDigital\Capicom\CAPICOM_TLB.pas',
  URelParcelasBloqueadas in '..\Financeiro\URelParcelasBloqueadas.pas' {FRelParcelasBloqueadas},
  UConfArqsTJSP in '..\Juridico\UConfArqsTJSP.pas' {FConfArqsTJSP},
  URelCadOSMobiliario in '..\Serviços\URelCadOSMobiliario.pas' {FRelOSMobiliario},
  UAddDocPetIntermediario in '..\Juridico\UAddDocPetIntermediario.pas' {FAddDocPetIntermediario},
  UAJItensTrabalho in '..\Juridico\UAJItensTrabalho.pas' {FAJItensTrabalho},
  UCadTransfReceitas in '..\Financeiro\UCadTransfReceitas.pas' {FCadTransfReceitas},
  UDesisteCDA in '..\Financeiro\UDesisteCDA.pas' {FDesisteCDA},
  URelTransfReceitas in '..\Financeiro\URelTransfReceitas.pas' {RelTransfReceitas},
  UClasse_Almox_SIA in '..\Agua\UClasse_Almox_SIA.pas',
  URelFiscais in '..\Serviços\URelFiscais.pas' {FRelFiscais},
  UCadEncerraOSAG in '..\Serviços\UCadEncerraOSAG.pas' {FCadEncerraOSAG},
  UCadCancelaOSAG in '..\Serviços\UCadCancelaOSAG.pas' {FCadCancelaOSAG},
  UConsProdutosAG in '..\Agua\UConsProdutosAG.pas' {FConsProdutosAG},
  UHisSubLimite in '..\Mobiliario\UHisSubLimite.pas' {FHisSubLimite},
  UCadImobiliarias in '..\Imobiliario\UCadImobiliarias.pas' {FCadImobiliarias},
  URelImobiliarias in '..\Imobiliario\URelImobiliarias.pas' {FRelImobiliarias},
  USelecaoCheckBox in '..\Diversas\USelecaoCheckBox.pas' {FSelecaoCheckBox},
  UMenuConsBR in '..\Principal\UMenuConsBR.pas' {FMenuConsBR},
  f_pesquisa_cadsus in '..\Principal\f_pesquisa_cadsus.pas' {frmPesq_Paciente_CNS},
  URecPrincipal in '..\Financeiro\URecPrincipal.pas' {FRecPrincipal},
  UCadTPSolicitante in '..\Serviços\UCadTPSolicitante.pas' {FCadTPSolicitante},
  URelTipoSolicitante in '..\Serviços\URelTipoSolicitante.pas' {FRelTipoSolicitante},
  UDMArquivos in '..\Principal\UDMArquivos.pas' {DMArq: TDataModule},
  UCadImagemDocs in '..\Principal\UCadImagemDocs.pas' {FCadImagemDocs},
  UCadResponsavelObra in '..\Serviços\UCadResponsavelObra.pas' {FCadResponsavelObra},
  URelResponsavelObra in '..\Serviços\URelResponsavelObra.pas' {FRelResponsavelObra},
  UClasse_Arquivos in '..\Principal\UClasse_Arquivos.pas',
  URelDetParcela in '..\Financeiro\URelDetParcela.pas' {FRelDetParcela},
  UCadTipoAnexos in '..\Principal\UCadTipoAnexos.pas' {FCadTipoAnexos},
  UInscrDAFinManual in '..\Financeiro\UInscrDAFinManual.pas' {FInscrDAFinManual},
  UMenuCarga in '..\Juridico\UMenuCarga.pas' {FMenuCarga},
  UAJCadCargas in '..\Juridico\UAJCadCargas.pas' {FAJCadCargas},
  UAJRelCargasProc in '..\Juridico\UAJRelCargasProc.pas' {FAJRelCargasProc},
  UFrameGIF in '..\Principal\UFrameGIF.pas' {FFrameGIF: TFrame},
  UXmlSolicitaIntimacao in '..\Financeiro\UXmlSolicitaIntimacao.pas',
  UAJCadTramitesEmb in '..\Juridico\UAJCadTramitesEmb.pas' {FAJCadTramitesEmb},
  UAJCadEmbargos in '..\Juridico\UAJCadEmbargos.pas' {FAJCadEmbargos},
  UConsCRTAGU in '..\Agua\UConsCRTAGU.pas' {FConsCRTAGU},
  UConsCRTMOB in '..\Mobiliario\UConsCRTMOB.pas' {FConsCRTMOB},
  UConsulta in '..\Principal\UConsulta.pas' {FConsultas},
  URelLograRel in '..\Principal\URelLograRel.pas' {FRelLograRel},
  UFrameCaract in '..\Principal\UFrameCaract.pas' {FFrameCaract: TFrame},
  UMostraResultados in '..\Principal\UMostraResultados.pas' {FMostraResultados},
  funcoesTela in '..\Principal\funcoesTela.pas',
  UCriaOrdenacao in '..\Principal\UCriaOrdenacao.pas' {FCriaOrdenacao},
  UDMDebito in '..\Principal\UDMDebito.pas' {DMDebito: TDataModule},
  UFrameGuia in '..\Financeiro\UFrameGuia.pas' {FFrameGuia: TFrame},
  UConsultaDebito in '..\Financeiro\UConsultaDebito.pas' {FConsultaDebito},
  UGNotificaPostura in '..\Serviços\UGNotificaPostura.pas' {FGNotificaPostura},
  UConsultaSAJ in '..\Juridico\UConsultaSAJ.pas' {FConsultaSAJ},
  UClasse_Debito in '..\Principal\UClasse_Debito.pas',
  UMostraHistorico in '..\Principal\UMostraHistorico.pas' {FMostraHistorico},
  URelOSCorte in '..\Agua\URelOSCorte.pas' {FRelOSCorte},
  USelCadOSCorte in '..\Agua\USelCadOSCorte.pas' {FSelCadOSCorte},
  UCadEncerraOSCorte in '..\Agua\UCadEncerraOSCorte.pas' {FCadEncerraOSCorte},
  UGeraOrdemCorte in '..\Agua\UGeraOrdemCorte.pas' {FGeraOrdemCorte},
  UHistoricoCorte in '..\Agua\UHistoricoCorte.pas' {FHistoricoCorte},
  UCadIntimacoes in '..\Juridico\UCadIntimacoes.pas' {FCadIntimacoes},
  USuspendeDividas in '..\Financeiro\USuspendeDividas.pas' {FSuspendeDividas},
  UConsNotificacaoAG in '..\Agua\UConsNotificacaoAG.pas' {FConsNotificacaoAG},
  UConsProdutosSCPI in '..\Agua\UConsProdutosSCPI.pas' {FConsProdutosSCPI},
  URelPedidoVistoria in '..\Agua\URelPedidoVistoria.pas' {FRelPedidoVistoria},
  UCadRetornoVistoria in '..\Agua\UCadRetornoVistoria.pas' {FCadRetornoVistoria},
  URelRetiradaMaterial in '..\Agua\URelRetiradaMaterial.pas' {FRelRetiradaMaterial},
  UFRelProtocoloReq in '..\Protocolo\UFRelProtocoloReq.pas' {FRelProtocoloReq},
  UdmRelatorios in '..\Protocolo\UdmRelatorios.pas' {dmRelatorios: TDataModule},
  UExportaPDF in '..\Juridico\UExportaPDF.pas',
  UAJConsForoTJSP in '..\Juridico\UAJConsForoTJSP.pas' {FAJConsForoTJSP},
  UAguardePermissao in '..\Principal\UAguardePermissao.pas' {FAguardePermissao},
  URelTermoInscricaoDivida in '..\Financeiro\URelTermoInscricaoDivida.pas' {FRelTermoInscricaoDivida},
  UEstornaSuspendeDividas in '..\Financeiro\UEstornaSuspendeDividas.pas' {FEstornaSuspendeDividas};

{$R *.res}

var Handel : HWND;

begin
  Application.Initialize; //
  ShortDateFormat := 'dd/mm/yyyy';

  // Usando isso não abrir o sistema mais de uma vez dentro do datacenter
  if dm.ehDataCenter then begin
    Handel := FindWindow(Nil, PChar('Rural Fiorilli'));
    if Handel > 0 then begin
      ShowWindow(Handel, SW_RESTORE);
      exit;
    end;
  end;

  // isto aqui é usado para esconder os DataModules da inicialização do Projeto. se abrir o menu/Project do delphi verá que nenhum dm estara listado.
  if ParamStr(2) = 'design' then begin
    Application.CreateForm(TFrmPKG, FrmPKG);
  FrmPKG.showModal;
    FrmPKG.free;
  end;

  Application.Title := 'Rural Fiorilli';
  Application.CreateForm(TDMAgua, DMAgua);
  Application.CreateForm(TDMOS, DMOS);
  Application.CreateForm(TDMF, DMF);
  Application.CreateForm(TDMIPTU, DMIPTU);
  Application.CreateForm(TDMMOBI, DMMOBI);
  Application.CreateForm(TdmLog, dmLog);
  Application.CreateForm(TdmFin, dmFin);
  Application.CreateForm(TdmSSE, dmSSE);
  Application.CreateForm(TdmRelatorios, dmRelatorios);
  Application.CreateForm(TDMMAPIMail, DMMAPIMail);
  Application.CreateForm(TdmDSnapAG, dmDSnapAG);
  Application.CreateForm(TrvActionsResource, rvActionsResource);
  Application.CreateForm(TdmServ, dmServ);
  Application.CreateForm(TdmPrin, dmPrin);
  Application.CreateForm(TdmJur, dmJur);
  Application.CreateForm(TdmSLog, dmSLog);
  Application.CreateForm(TdmARQ, dmARQ);
  Application.CreateForm(TdmDebito, dmDebito);
  Application.CreateForm(Tdm, dm);
  Application.CreateForm(TFPrin, FPrin);
  FPrin.Tag := 1;

  if ParamStr(2) = 'menus' then begin
    Application.CreateForm(TFAguardeSimples, FAguardeSimples);
    FAguardeSimples.L2.Caption := 'carregando';
    FAguardeSimples.Show;
    dm.GravaMenusTabDef(FPrin, FPrin.ActionList1, FPrin.MainMenu1, 'RURAL');
    FreeAndNil(FAguardeSimples);
    FPrin.Tag := 0;
  end;

  if FileExists(CaminhoDB('D') + 'BK.DAT') Then begin
    showmessage(' Foi detectado que o Backup está sendo Efetuado, caso não esteja, '+#13+
                'entre em : '+ CaminhoDB('D') +' e apague o arquivo BK.DAT');
    FPrin.Tag := 0;
  end;

  if FPrin.Tag = 1 then
    Application.Run
  else begin
    FreeAndNil(DMAgua);
    FreeAndNil(DMOS);
    FreeAndNil(DMF);
    FreeAndNil(DMIPTU);
    FreeAndNil(DMMOBI);
    FreeAndNil(dmLog);
    FreeAndNil(dmFin);
    FreeAndNil(dmSSE);
    FreeAndNil(DMRelatorios);
    FreeAndNil(DMMAPIMail);
    FreeAndNil(dmDSnapAG);
    FreeAndNil(rvActionsResource);
    FreeAndNil(dmServ);
    FreeAndNil(dmPrin);
    FreeAndNil(dmJur);
    FreeAndNil(dmSLog);
    FreeAndNil(dmARQ);
    FreeAndNil(dmDebito);
    FreeAndNil(dm);
    FreeAndNil(FPrin);
    Application.Terminate;
  end;
end.
